# Generated by Django 2.2.4 on 2019-10-15 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('build_date', models.IntegerField()),
                ('build_type', models.CharField(max_length=32)),
                ('device', models.CharField(max_length=32)),
                ('dish', models.CharField(max_length=32)),
                ('downloads', models.IntegerField(default=0)),
                ('filename', models.CharField(max_length=128, unique=True)),
                ('md5', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True, max_length=256, null=True)),
                ('size', models.IntegerField()),
                ('version', models.CharField(max_length=32)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
