# Generated by Django 2.1.8 on 2019-06-02 17:00

import django.core.files.storage
from django.db import migrations, models
import ota.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='http://www.google.de/', location='C:\\Users\\nicof\\Desktop\\Python\\potatoapi\\public\\ota'), upload_to=ota.models.build_file_path, validators=[ota.models.validate_file_extension])),
                ('build_date', models.IntegerField()),
                ('build_type', models.CharField(max_length=32)),
                ('device', models.CharField(max_length=32)),
                ('downloads', models.IntegerField()),
                ('filename', models.CharField(max_length=128, unique=True)),
                ('private', models.BooleanField(default=False)),
                ('size', models.IntegerField()),
                ('version', models.CharField(max_length=32)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
