# Generated by Django 2.1.8 on 2019-06-03 11:56

import django.core.files.storage
from django.db import migrations, models
import ota.models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0002_build_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='build',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/api/ota/downloads', location='C:\\Users\\nicof\\Desktop\\Python\\potatoapi\\public\\ota'), upload_to=ota.models.build_file_path, validators=[ota.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='build',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
