# Generated by Django 2.2.4 on 2019-09-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0002_build_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='dish',
            field=models.CharField(default='Baked', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='build',
            name='notes',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
