# Generated by Django 3.0.1 on 2019-12-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0003_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='notes',
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
    ]
