# Generated by Django 2.2.2 on 2019-06-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota', '0003_auto_20190603_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='md5',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
    ]
