# Generated by Django 2.1.8 on 2019-06-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='maintainer',
            field=models.BooleanField(default=False),
        ),
    ]
