# Generated by Django 2.1.8 on 2019-06-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_maintainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='maintainer',
            new_name='is_maintainer',
        ),
    ]
