# Generated by Django 2.2.2 on 2019-06-04 11:24

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190603_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.user_image_file_path),
        ),
    ]
